### PR TITLE
Feature/team1 issue67 reactpage users

### PR DESCRIPTION
**Pull request by jak-ashuraliev**

### CODE REVIEW

**Review by farhadbahrehmandhenry — APPROVED** [review]
works like a charm, good to merge.

**Review by theKunte — APPROVED** [review]
Just tested your PR. Works well and its good to go. I was able to see the users  table with all users

**Comment by theKunte** [comment]
You just need to resolve the conflicts and you are good to go! Good job!

**Comment by jak-ashuraliev** [comment]
Good to Go!

**Pull request merged**
