### PR TITLE
GitHub Actions auto-deploy azure functions

### LINKED ISSUE #14: [Task] Deploy function code to azure when Pull Request is completed (GH Actions)
**Is your feature request related to a problem? Please describe.**
When Azure functions are updated on GitHub, that update does not automatically carry over to the deployed functions. Updating must currently be done manually, which adds unnecessary extra steps. 

**Describe the solution you'd like**
Use GitHub actions to automatically update deployed Azure functions when a PR is completed from the development branch.

**Describe alternatives you've considered**
There are a multitude of different CI/CD tools from CircleCI to Azure's own implementation. I believe that GitHub actions is appropriate for the current context because it is free for open source projects (ours) and because it integrates nicely with our GitHub project.

**Additional context**
None.

**Acceptance Criteria**
- [x] A GitHub action that updates our functions on Azure runs when the development branch is updated.

### PR DESCRIPTION
**Pull request by lbrown51**
Resolves #14 
- This GitHub actions script will run when a pr is merged into the development branch
- How it works
  - Start doing the build and deploy job which runs on the latest ubuntu version
  - Checkout the repository
  - Setup the version of python set in our script environment
  - Install all the necessary python packages using pip
  - Deploy to Azure Functions with
    - The name of the app established in the GitHub secrets under AZURE_FUNCTIONAPP_NAME
    - The publish profile of the function app established in GitHub secrets under AZURE_FUNCTIONAPP_PUBLISH_PROFILE
    - The path in our repository where the functions reside
- The repo path and the python version are not currently set to be secrets (I think that's what GitHub uses for all environment variables), but they easily could be if necessary)
- Both of those settings sit in the environment part of the deploy yaml script
- **Troubleshooting**: the only error I ran into was when the publish profile settings where not correctly copied into the GitHub secrets area. If you start getting permissions / login errors in Actions, that's probably what's causing it.

[This is what it looks like when it works](https://github.com/theKunte/ad440-winter2021-thursday-repo/actions/runs/486904223)

|**DATE**|**ACTIVITY**|**TIME**|
  |---|:---|:---|
  |1/8|Thinking about the steps necessary to start researching (I'm serious here)|30 minutes|
  |1/9|More thinking about how to research|60 minutes|
  |1/11|Started reading about GitHub Actions|30 minutes|
  |1/11|Started reading about Azure Functions + Deployment|30 minutes|
  |1/13|Created a separate repo to test out github actions|60 minutes|
  |1/13|Continued working on separate repo to test out github actions + function deployment|60 minutes|
  |1/14|Finished up prototyping and transferred code over to fork|30 minutes|
  |1/14|Nothing worked, started troubleshooting|30 minutes|
  |1/14|Turned out to be publish profile error, once fixed, worked on adapting more to repo|30 minutes|
  |1/14|Finished up prototyping and transferred code over to fork|30 minutes|
  |1/14|Tested out how it would work if triggered on PR instead of push|30 minutes|
  |1/14|Wrote comments|30 minutes|
  |1/17|Did a bunch of small changes|30 minutes|
  |1/18|Wrote this PR|1 hour|

### CODE REVIEW

**Review by farhadbahrehmandhenry — COMMENTED** [review]
I have a couple of questions here =>
1- it seems the only file you added is "deployAzureFunctions.yaml", however you have other files related to azure functions in your pr. do you need to have all of these files in your pr? the reason I'm asking is that it's not clear which file you've worked on.
2- I saw you've set up the actions on the forked repo. do we need to have those actions set up in the NSC repo as well, since we merge our stuff in the NSC development branch, not in the forked branch? 
thanks.

**Comment by theKunte** [comment]
Looks like there is additional files pushed up that should not be included. I had the same issue and removed the files from my PR. Not sure if there is a better way to remove the files. Otherwise, the script looks good. I am curious how the GithubAction. 
Like Farhad mentioned above. Where you able to set up the actions on the NSC repo?

**Comment by lbrown51** [comment]
@farhadbahrehmandhenry good question, I was already thinking of getting rid of them from the PR. The only reason I included them is that we won't really know if the PR works without having some kind of function, but that's probably alright since the rest of the team 1 stuff is incoming anyways. I'll get rid of it.

@theKunte this file actually sets up the action. The only thing that needs to be done is for Toddy to add the secrets to the NSC GitHub. I'm gonna message him about that now. I'll do it for the team 1 repo that you made.

**Review by farhadbahrehmandhenry — APPROVED** [review]

**Review by theKunte — APPROVED** [review]

**Comment by theKunte** [comment]
branch has been cleand up! Like Lenny mentioned the only thing is to add the secrets to NSC repo once its merged

**Pull request merged**
