### PR TITLE
Team 4 task: Serverless -artillery report for endpoint \users

### PR DESCRIPTION
**Pull request by chonger878**
Add a github action that will run a serverless-artillery report for the endpoint user.  This can be used to generate a list of users that can be pulled into a json file or data bucket.

### CODE REVIEW

**Review by StopMakingUsernamesUnique — APPROVED** [review]
Great, try including a -rampTo phase so we can stress test

**Review by StopMakingUsernamesUnique — APPROVED** [review]
I don't think we are using the stage names anymore, I think we are using region instead, check the perf test kevin has that is now working

**Comment by chonger878** [comment]
@StopMakingUsernamesUnique , I can't seem to locate that perf test.  What issue did it cover?

**Review by jaguiniga — APPROVED** [review]
Other than the permissions it looks like it should work.

**Pull request merged**
