### PR TITLE
Get the artillery results from S3 bucket and render in React for /users/{user_id}

### LINKED ISSUE #91: [TASK] Get the artillery results from S3 bucket and render in React for /users/{user_id}
**Is your feature request related to a problem? Please describe.**
Task is to display the serverless-artillery report for /users/{user_id} in the react ui.

**Describe the solution you'd like**
Create a react component and add it to the router.

**Describe alternatives you've considered**
Considered using the bootstrap table, but I went with a module to process the json into a table to decouple the issue. Now if the json data changes, the component will still render.

### PR DESCRIPTION
**Pull request by zxkevinxz**
Closes #91 - Team 3

# Get the artillery results from S3 bucket and render in React for /users/{user_id}
- Created a folder structure for the reports within the routes folder
- Added the route, and listed it on the home page
- The component currently fetches some sample json data because the current url for the needed data is unknown at this time. Once that is available, the jsonUrl on line 6 in /ui/react-ui/src/components/routes/reports/userIdReport/UserIdReport.js can be updated to the proper one.
- Used React function component and react hooks for state, and fetching.
- Added package 'react-json-to-table" for processing the json into a table. I decided on using this over designing a table because if the json data changes, this will still process it properly. If better table headers are wanted/needed, the keys in the json data can be changed to reflect the proper headers.
- added button toggle from table to json because report test data can be unruly and make the table very wide.

### Testing
- navigate to /ui/react-ui
- run "npm install" in the command line to make sure all packages are up to date
- "npm start" in the command line to start the react app
- Open browser to localhost:3000 (most likely 3000, but could be different on your machine)
- You will see the route listed on the home page
- Navigate to localhost:3000/reports/userId
- You will see the table load with the current dummy data

Screen Shot 2021-02-03 at 12 14 58 AM

|**DATE**|**ACTIVITY**|**TIME**|
|---|:---|:---|
|2/2|Created react component|1.5 hours|
|2/2|Tested and wrote PR|.5 hours|
|2/2|Made updates and button|1 hour|

### CODE REVIEW

**Comment by ahmadafrasiyab** [comment]
I am able to run it. Thats great. However, a few things came up. One, maybe we want the test results endpoints to be displayed in a different block of their own so this display is a bit confusing. Its not a ui class sure, but maybe we can move them together where it says "Test reports endpoints" and then all four endpoints under them.
image

**Comment by zxkevinxz** [comment]
> I am able to run it. Thats great. However, a few things came up. One, maybe we want the test results endpoints to be displayed in a different block of their own as this display is a bit confusing. Its not a ui class sure, but maybe we can move them together where it says "Test reports endpoints" and then all four endpoints under them.
> image

I made a section for Test Results, also updated to use the report json you had on the bucket.

**Comment by ahmadafrasiyab** [comment]
I pulled it again and runs good. The button adds good flexibility. Endpoints are now separately showing which is reasonable. There are actual test results which is better than dummy data. I am approving this.

**Review by ahmadafrasiyab — APPROVED** [review]

**Review by natni — APPROVED** [review]
Looks great! Tested it and it works.

**Pull request merged**
